name: Cody Style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-cov:
    name: CodeCov
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./build/logs/
          files: clover.xml
          flags: tests
          fail_ci_if_error: true
          verbose: true
